#!/usr/bin/env bash

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

FIFO="${FIFO:-/run/shutdown-fifo}"

cleanup() {
	trap - SIGINT SIGTERM ERR EXIT
	# rm -f $FIFO
}

[ -p $FIFO ] || mkfifo $FIFO;

setfacl -m u::r,u:1000:w $FIFO

while true
do
	if read line; then
		echo "SHUTTING DOWN"	
		exit
	fi
done <"$FIFO"